name: CI/CD 

on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu cần thiết

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Sử dụng PHP phiên bản 8.0

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit 
        run: ./vendor/bin/phpunit

      # Thêm bước build để tạo các tệp tĩnh
      - name: Build static site
        run: npm run build  # hoặc lệnh build tương ứng cho dự án của bạn

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_site  # Thư mục chứa các tệp tĩnh sau khi build
