name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Adjust to your PHP version

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: |
          # Replace with your test command (e.g., PHPUnit)
          phpunit

      - name: Deploy to staging
        if: success()
        run: |
          # Replace with your deployment script or commands
          # Example: Deploy to staging server using SSH
          ssh user@staging-server 'cd /path/to/project && git pull origin main && composer install && php artisan migrate'

