name: PHP_CodeSniffer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: List composer dependencies
        run: composer show

      - name: Check vendor directory
        run: ls -la ./vendor

      - name: Check bin directory
        run: ls -la ./vendor/bin

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=phpcs.xml.dist .
